#!/usr/bin/env bash
# Terraform import handoff for fresh-edge resources (operator side).
#
# The fresh runner creates edge resources via the Cloudflare API (tunnel,
# DNS records, Access apps/policies) because no Terraform state exists for a
# host that does not exist yet. This script closes the IaC loop: it reads the
# handoff JSON written by scripts/wire-fresh-edge.sh --handoff-file and emits
# exact `import {}` blocks (verified provider-v5.25 ID formats) plus the
# follow-up commands, so the API-created edge is adopted into Terraform state
# instead of diverging from it.
#
# Convention: fresh resources land under `fresh_*` addresses; the operator
# adds matching resource blocks (copying the preserved ones in
# infra/terraform/main.tf with the fresh hostnames) and runs the printed
# `terraform import` commands, then `terraform plan` must show no changes.
#
# Usage:
#   bash scripts/emit-fresh-imports.sh --handoff PATH [--dry-run]
set -euo pipefail

dry_run=0
handoff=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) dry_run=1; shift ;;
    --handoff) handoff="$2"; shift 2 ;;
    --handoff=*) handoff="${1#--handoff=}"; shift ;;
    -h|--help) echo 'usage: emit-fresh-imports.sh --handoff PATH [--dry-run]'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$handoff" ] && [ -f "$handoff" ] || { echo 'handoff JSON file required (--handoff PATH).' >&2; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo 'python3 is required.' >&2; exit 2; }
[ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ] || { echo 'CLOUDFLARE_ACCOUNT_ID must be set.' >&2; exit 2; }
[ -n "${CLOUDFLARE_ZONE_ID:-}" ] || { echo 'CLOUDFLARE_ZONE_ID must be set.' >&2; exit 2; }

if [ "$dry_run" -eq 1 ]; then
  echo 'DRY-RUN: validate handoff JSON schema + print import blocks (no state touched)'
  exit 0
fi

python3 - "$handoff" "$CLOUDFLARE_ACCOUNT_ID" "$CLOUDFLARE_ZONE_ID" <<'PYEOF'
import json, sys
handoff_path, acct, zone = sys.argv[1], sys.argv[2], sys.argv[3]
h = json.load(open(handoff_path))
assert isinstance(h.get('tunnel_id'), str) and h['tunnel_id'], 'handoff: tunnel_id missing'
assert isinstance(h.get('routes'), list) and h['routes'], 'handoff: routes missing'
print('# Generated by scripts/emit-fresh-imports.sh — append to infra/terraform/imports.tf,')
print('# add matching fresh_* resource blocks (copies of the preserved ones with fresh')
print('# hostnames), then run the terraform import commands below.')
print()
tid = h['tunnel_id']
print('import {')
print('  to = cloudflare_zero_trust_tunnel.fresh')
print(f'  id = "{acct}/{tid}"')
print('}')
print('import {')
print('  to = cloudflare_zero_trust_tunnel_cloudflared_config.fresh')
print(f'  id = "{acct}/{tid}"')
print('}')
for r in h['routes']:
    slug = r['hostname'].split('.')[0].replace('-', '_')
    assert r.get('dns_record_id'), f"handoff: dns_record_id missing for {r['hostname']}"
    assert r.get('access_app_id'), f"handoff: access_app_id missing for {r['hostname']}"
    print('import {')
    print(f'  to = cloudflare_dns_record.fresh_{slug}')
    print(f'  id = "{zone}/{r["dns_record_id"]}"')
    print('}')
    print('import {')
    print(f'  to = cloudflare_zero_trust_access_application.fresh_{slug}')
    print(f'  id = "accounts/{acct}/{r["access_app_id"]}"')
    print('}')
    for i, pid in enumerate(r.get('policy_ids', [])):
        print('import {')
        print(f'  to = cloudflare_zero_trust_access_policy.fresh_{slug}_{i}')
        print(f'  id = "accounts/{acct}/{r["access_app_id"]}/{pid}"')
        print('}')
print()
print('# Follow-up: terraform init -backend-config=backend.hcl && terraform plan')
print('# must show only the fresh_* additions converging, then no changes.')
PYEOF
