#!/usr/bin/env bash
# Fresh-edge IaC adoption (operator side): handoff JSON -> complete config.
#
# The fresh runner creates edge resources via the Cloudflare API (no state
# exists for a host that does not exist yet). This script closes the loop
# WITHOUT manual authoring: it reads the handoff JSON from
# scripts/wire-fresh-edge.sh --handoff-file and GENERATES the complete
# infra/terraform-fresh configuration (main.tf + imports.tf, both gitignored)
# using the same provider resources and conventions as infra/terraform/main.tf
# (nested Access policies, non_identity machine decision, http_status:404
# catch-all). The operator adds no blocks by hand: generate, plan, apply.
#
# The shared machine service token is referenced by ID variable only (never
# managed here); the VPS itself stays runner-managed. scripts/adopt-fresh-edge.sh
# wraps this with init/plan/apply.
#
# Usage:
#   CLOUDFLARE_ACCOUNT_ID=... CLOUDFLARE_ZONE_ID=... \
#   bash scripts/emit-fresh-imports.sh --handoff PATH [--dry-run] [--out-dir DIR]
set -euo pipefail

dry_run=0
handoff=''
out_dir='infra/terraform-fresh'
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) dry_run=1; shift ;;
    --handoff) handoff="$2"; shift 2 ;;
    --handoff=*) handoff="${1#--handoff=}"; shift ;;
    --out-dir) out_dir="$2"; shift 2 ;;
    --out-dir=*) out_dir="${1#--out-dir=}"; shift ;;
    -h|--help) echo 'usage: emit-fresh-imports.sh --handoff PATH [--dry-run] [--out-dir DIR]'; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done
[ -n "$handoff" ] && [ -f "$handoff" ] || { echo 'handoff JSON file required (--handoff PATH).' >&2; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo 'python3 is required.' >&2; exit 2; }
[ -n "${CLOUDFLARE_ACCOUNT_ID:-}" ] || { echo 'CLOUDFLARE_ACCOUNT_ID must be set.' >&2; exit 2; }
[ -n "${CLOUDFLARE_ZONE_ID:-}" ] || { echo 'CLOUDFLARE_ZONE_ID must be set.' >&2; exit 2; }

if [ "$dry_run" -eq 1 ]; then
  echo 'DRY-RUN: validate handoff JSON schema + print summary (no files written)'
  python3 - "$handoff" <<'PYEOF'
import json, sys
h = json.load(open(sys.argv[1]))
assert isinstance(h.get('tunnel_id'), str) and h['tunnel_id'], 'handoff: tunnel_id missing'
assert isinstance(h.get('tunnel_name'), str) and h['tunnel_name'], 'handoff: tunnel_name missing'
assert isinstance(h.get('routes'), list) and h['routes'], 'handoff: routes missing'
for r in h['routes']:
    assert r.get('dns_record_id') and r.get('access_app_id'), f"handoff: ids missing for {r.get('hostname')}"
print(f"handoff ok: tunnel {h['tunnel_name']} + {len(h['routes'])} routes")
PYEOF
  exit 0
fi

python3 - "$handoff" "$CLOUDFLARE_ACCOUNT_ID" "$CLOUDFLARE_ZONE_ID" "$out_dir" <<'PYEOF'
import json, os, sys

handoff_path, acct, zone, out_dir = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
h = json.load(open(handoff_path))
assert isinstance(h.get('tunnel_id'), str) and h['tunnel_id'], 'handoff: tunnel_id missing'
assert isinstance(h.get('tunnel_name'), str) and h['tunnel_name'], 'handoff: tunnel_name missing'
assert isinstance(h.get('routes'), list) and h['routes'], 'handoff: routes missing'
tid, tname = h['tunnel_id'], h['tunnel_name']
os.makedirs(out_dir, exist_ok=True)

def slug(hostname):
    return hostname.split('.')[0].replace('-', '_')

# --- main.tf: full resources, preserved conventions ---
main = []
main.append('# GENERATED by scripts/emit-fresh-imports.sh — do not hand-edit.')
main.append('# Regenerate from the handoff JSON after any API-side change.')
main.append('')
main.append('resource "cloudflare_zero_trust_tunnel_cloudflared" "fresh" {')
main.append('  account_id    = var.cloudflare_account_id')
main.append(f'  name          = "{tname}"')
main.append('  config_src    = "cloudflare"')
main.append('  tunnel_secret = "managed-outside-terraform"')
main.append('')
main.append('  lifecycle {')
main.append('    ignore_changes = [tunnel_secret]')
main.append('    prevent_destroy = true')
main.append('  }')
main.append('}')
main.append('')
ingress = []
for r in h['routes']:
    ingress.append('      {')
    ingress.append(f'        hostname = "{r["hostname"]}"')
    ingress.append(f'        service  = "{r["service"]}"')
    ingress.append('      },')
ingress.append('      {')
ingress.append('        service = "http_status:404"')
ingress.append('      }')
main.append('resource "cloudflare_zero_trust_tunnel_cloudflared_config" "fresh" {')
main.append('  account_id = var.cloudflare_account_id')
main.append('  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.fresh.id')
main.append('  source     = "cloudflare"')
main.append('')
main.append('  config = {')
main.append('    ingress = [')
main.extend(ingress)
main.append('    ]')
main.append('  }')
main.append('}')
for r in h['routes']:
    s = slug(r['hostname'])
    title = 'Coolify Dashboard' if r['service'].startswith('http') else 'Coolify SSH Administration'
    main.append('')
    main.append(f'resource "cloudflare_dns_record" "fresh_{s}" {{')
    main.append('  zone_id = var.cloudflare_zone_id')
    main.append(f'  name    = "{r["hostname"]}"')
    main.append('  type    = "CNAME"')
    main.append('  content = "${cloudflare_zero_trust_tunnel_cloudflared.fresh.id}.cfargotunnel.com"')
    main.append('  ttl     = 1')
    main.append('  proxied = true')
    main.append(f'  comment = "Fresh {r["hostname"]} through the Cloudflare Tunnel; managed by Terraform."')
    main.append('}')
    main.append('')
    main.append(f'resource "cloudflare_zero_trust_access_application" "fresh_{s}" {{')
    main.append('  account_id                = var.cloudflare_account_id')
    main.append(f'  name                      = "Fresh {title}"')
    main.append(f'  domain                    = "{r["hostname"]}"')
    main.append('  type                      = "self_hosted"')
    main.append('  allowed_idps              = []')
    main.append('  auto_redirect_to_identity = false')
    main.append('  enable_binding_cookie     = true')
    main.append('  options_preflight_bypass  = false')
    main.append('  session_duration          = "24h"')
    main.append('  policies = concat(')
    main.append('    [{')
    main.append('      name       = "Allow machine service token"')
    main.append('      decision   = "non_identity"')
    main.append('      precedence = 1')
    main.append('      include = [{')
    main.append('        service_token = {')
    main.append('          token_id = var.service_token_id')
    main.append('        }')
    main.append('      }]')
    main.append('    }],')
    main.append('    [')
    main.append('      for position, email in sort(tolist(var.admin_emails)) : {')
    main.append('        name       = "Allow ${email}"')
    main.append('        decision   = "allow"')
    main.append('        precedence = position + 2')
    main.append('        include = [{')
    main.append('          email = {')
    main.append('            email = email')
    main.append('          }')
    main.append('        }]')
    main.append('      }')
    main.append('    ]')
    main.append('  )')
    main.append('}')
open(os.path.join(out_dir, 'main.tf'), 'w').write('\n'.join(main) + '\n')

# --- imports.tf: adoption blocks, verified v5.25 ID formats ---
imp = []
imp.append('# GENERATED by scripts/emit-fresh-imports.sh — adoption blocks.')
imp.append('# terraform plan/apply adopts the API-created edge into state.')
imp.append('')
imp.append('import {')
imp.append('  to = cloudflare_zero_trust_tunnel_cloudflared.fresh')
imp.append(f'  id = "{acct}/{tid}"')
imp.append('}')
imp.append('import {')
imp.append('  to = cloudflare_zero_trust_tunnel_cloudflared_config.fresh')
imp.append(f'  id = "{acct}/{tid}"')
imp.append('}')
for r in h['routes']:
    s = slug(r['hostname'])
    imp.append('import {')
    imp.append(f'  to = cloudflare_dns_record.fresh_{s}')
    imp.append(f'  id = "{zone}/{r["dns_record_id"]}"')
    imp.append('}')
    imp.append('import {')
    imp.append(f'  to = cloudflare_zero_trust_access_application.fresh_{s}')
    imp.append(f'  id = "accounts/{acct}/{r["access_app_id"]}"')
    imp.append('}')
open(os.path.join(out_dir, 'imports.tf'), 'w').write('\n'.join(imp) + '\n')
print(f'generated {out_dir}/main.tf + {out_dir}/imports.tf ({len(h["routes"])} routes)')
PYEOF
