#!/usr/bin/env bash
# Generate the ignored Terraform credential files from OpenBao + OVH CLI.
#
# The Terraform module takes provider authorization as variables (versions.tf
# declares no credential defaults by design). This loader is the noninteractive
# bridge: it retrieves every credential-bearing value through the existing
# OpenBao workflow plus read-only OVH CLI discovery, and writes them only to
# ignored local files. No browser, no dashboard, no hand-editing tfvars.
#
# Reads (OpenBao, by name only; values never printed):
#   ADMIN_CLOUDFLARE / COOLIFY_TUNNEL_SECRET.tunnel_secret / runner token file
# Reads (OVH CLI discovery): service name + IPv4 of the preserved VPS.
# Writes: infra/terraform/terraform.tfvars (ignored), prints backend env
#   exports (AWS_* for the R2 state backend) for eval.
#
# Usage:
#   eval "$(BAO_ADDR=https://secrets.pkubelka.cz bash scripts/load-tfvars-from-openbao.sh)"
set -euo pipefail

dry_run=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) dry_run=1 ;;
    -h|--help) echo 'usage: load-tfvars-from-openbao.sh [--dry-run]'; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

log() { printf '%s\n' "$*" >&2; }
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
tfvars="$repo_root/infra/terraform/terraform.tfvars"

command -v bao >/dev/null 2>&1 || { echo 'bao CLI is required.' >&2; exit 2; }
command -v ovhcloud >/dev/null 2>&1 || { echo 'ovhcloud CLI is required for VPS discovery.' >&2; exit 2; }
bao_addr="${BAO_ADDR:-https://secrets.pkubelka.cz}"
export BAO_ADDR="$bao_addr"
bao_token_file="${BAO_TOKEN_FILE:-$HOME/.vault-token}"
if [ ! -f "$bao_token_file" ]; then
  echo "OpenBao runner token file not found: ${bao_token_file}." >&2
  exit 2
fi

if [ "$dry_run" -eq 1 ]; then
  log 'DRY-RUN: read ADMIN_CLOUDFLARE + tunnel_secret + runner token + R2 pair from OpenBao by name only'
  log 'DRY-RUN: discover VPS service name + IPv4 via read-only ovhcloud CLI'
  log 'DRY-RUN: write ignored 0600 terraform.tfvars; print backend AWS_* exports for eval (values never printed)'
  exit 0
fi
log 'retrieving provider authorization from OpenBao (names only)...'
cf_token="$(bao kv get -field=ADMIN_CLOUDFLARE secret/projects/ovhcloud/ADMIN_CLOUDFLARE)"
tunnel_secret="$(bao kv get -field=tunnel_secret secret/projects/ovhcloud/COOLIFY_TUNNEL_SECRET)"
bao_token="$(cat "$bao_token_file")"
r2_ak="$(bao kv get -field=access_key_id secret/projects/ovhcloud/COOLIFY_R2)"
r2_sk="$(bao kv get -field=secret_access_key secret/projects/ovhcloud/COOLIFY_R2)"
for v in cf_token tunnel_secret bao_token r2_ak r2_sk; do
  if [ -z "${!v}" ]; then echo "OpenBao escrow missing for ${v}; refusing to continue." >&2; exit 2; fi
done

log 'discovering preserved VPS identity via read-only OVH CLI...'
service_name="$(ovhcloud vps list --output json 2>/dev/null | jq -r '.[0].displayName // empty')"
if [ -z "$service_name" ]; then echo 'OVH VPS discovery returned no service.' >&2; exit 2; fi
ipv4="$(ovhcloud vps ip list "$service_name" --output json 2>/dev/null | jq -r '.[] | select(.version == "v4") | .ipAddress // empty' | head -n1)"
if [ -z "$ipv4" ]; then echo 'OVH IP discovery returned no IPv4.' >&2; exit 2; fi
log "discovered service ${service_name} (${ipv4}); values written, never printed."

umask 077
cat >"$tfvars" <<TFVARS_EOF
# GENERATED by scripts/load-tfvars-from-openbao.sh — ignored, never commit.
# Regenerate any time; values come from OpenBao + read-only OVH discovery.
cloudflare_api_token     = "${cf_token}"
cloudflare_account_id    = "5eb3ea3a84b37564cfd8739f32ffb559"
cloudflare_tunnel_secret = "${tunnel_secret}"
openbao_address          = "${bao_addr}"
openbao_token            = "${bao_token}"
domain                   = "pkubelka.cz"
ovh_ipv4                 = "${ipv4}"
ovh_service_name         = "${service_name}"
admin_emails             = ["ksonny4@gmail.com"]
r2_bucket_name           = "ovh-coolify-backups"
manage_application_wildcard = false
access_service_token_name = "ovh-coolify-machine-verification"
access_service_token_duration = "8760h"
provision_ovh_vps        = false
manage_existing_vps      = true
TFVARS_EOF
chmod 600 "$tfvars"
# Canonical formatting keeps `terraform fmt -check -recursive` green when the
# file exists locally; fmt prints nothing, so no values leak through it.
terraform fmt "$tfvars" >/dev/null 2>&1 || true
log "wrote ${tfvars} (0600, ignored, canonically formatted)."

# Backend (R2 state) credentials go to stdout as eval-able exports only.
printf 'export AWS_ACCESS_KEY_ID=%s\n' "$r2_ak"
printf 'export AWS_SECRET_ACCESS_KEY=%s\n' "$r2_sk"
printf '# eval this output, then: terraform init -backend-config=backend.hcl\n' >&2
