#!/usr/bin/env bash
# Noninteractive remote provisioning runner for a fresh Coolify host.
#
# This is the project runner/provider channel: instead of manually running
# local root scripts on the target (scp + ad-hoc ssh), the operator runs this
# ONE script and it executes the full chain remotely over SSH —
# bootstrap -> Coolify -> Tunnel/Access -> R2 backup schedule — with
# per-stage verification. All secrets come from OpenBao (via `bao` on this
# machine) or from explicitly supplied env; values are never printed, never
# committed, and travel to the target only through the encrypted SSH channel
# (600-permission env file, deleted afterwards on both ends).
#
# Prerequisites (operator side):
# - `bao` authenticated against BAO_ADDR (default https://secrets.pkubelka.cz)
#   with read access to secret/projects/ovhcloud/*.
# - SSH key with access to PROVISION_SSH_USER@PROVISION_HOST (for a fresh OVH
#   VPS: inject the public key at order/reinstall time via the OVH manager or
#   API; initial key injection is the one explicit operator prerequisite).
# - ROOT_USERNAME / ROOT_USER_EMAIL / ROOT_USER_PASSWORD in the environment
#   for first-admin bootstrap (generated by the operator, never stored here).
#
# Usage:
#   BAO_ADDR=https://secrets.pkubelka.cz \
#   PROVISION_HOST=fresh-host.example PROVISION_ZONE=example.com \
#   PROVISION_SSH_USER=ubuntu PROVISION_SSH_KEY=~/.ssh/ovh_coolify_ed25519 \
#   ROOT_USERNAME=admin ROOT_USER_EMAIL=admin@example.com ROOT_USER_PASSWORD='...' \
#   bash scripts/run-remote-provision.sh [--dry-run] [--stages bootstrap,coolify,edge,backup]
set -euo pipefail

dry_run=0
stages='bootstrap,coolify,edge,backup'
while [ "$#" -gt 0 ]; do
  case "$1" in
    --dry-run) dry_run=1; shift ;;
    --stages) stages="$2"; shift 2 ;;
    --stages=*) stages="${1#--stages=}"; shift ;;
    -h|--help)
      echo 'usage: run-remote-provision.sh [--dry-run] [--stages bootstrap,coolify,edge,backup]'
      exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf '%s\n' "$*"; }
run() {
  if [ "$dry_run" -eq 1 ]; then
    log "DRY-RUN: $*"
  else
    "$@"
  fi
}

host="${PROVISION_HOST:-}"
# Single explicit domain contract: the operator supplies the Cloudflare ZONE
# and the runner derives the dashboard hostname from it, so Coolify FQDN,
# Tunnel ingress/DNS, and every HTTP verification use the same hostname.
# (An earlier revision took a bare domain and configured https://${domain}
# while the tunnel verified https://coolify.${domain} — now impossible.)
zone="${PROVISION_ZONE:-}"
dashboard_host="${PROVISION_DASHBOARD_HOST:-}"
if [ -z "$dashboard_host" ] && [ -n "$zone" ]; then
  dashboard_host="coolify.${zone}"
fi
ssh_user="${PROVISION_SSH_USER:-ubuntu}"
ssh_key="${PROVISION_SSH_KEY:-}"
coolify_version="${COOLIFY_VERSION:-4.3.19}"
bao_addr="${BAO_ADDR:-https://secrets.pkubelka.cz}"
r2_endpoint="${R2_ENDPOINT:-https://5eb3ea3a84b37564cfd8739f32ffb559.r2.cloudflarestorage.com}"
if [ -z "$host" ] || [ -z "$zone" ] || [ -z "$dashboard_host" ]; then
  echo 'PROVISION_HOST and PROVISION_ZONE (or PROVISION_DASHBOARD_HOST) must be set.' >&2
  exit 2
fi
# Operator-side identity guard: resolve the target against the preserved OVH
# service identity (API-backed when available) before any network/secret
# access. No self-check here by design: the runner never runs on the target.
GUARD_SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=scripts/lib/preserved-guard.sh
source "${GUARD_SCRIPT_DIR}/lib/preserved-guard.sh"
refuse_preserved_host "$host" || exit 2
if [ -z "$ssh_key" ] || [ ! -e "$ssh_key" ]; then
  echo 'PROVISION_SSH_KEY must point at an existing private key.' >&2
  exit 2
fi
if [ "$dry_run" -eq 0 ] && { [ -z "${ROOT_USERNAME:-}" ] || [ -z "${ROOT_USER_EMAIL:-}" ] || [ -z "${ROOT_USER_PASSWORD:-}" ]; }; then
  echo 'ROOT_USERNAME, ROOT_USER_EMAIL and ROOT_USER_PASSWORD must be set for first-admin bootstrap.' >&2
  exit 2
fi

log "target host: ${host} (user ${ssh_user})"
log "zone: ${zone}; dashboard hostname: ${dashboard_host}"
log "derived hostname used consistently for Coolify FQDN, Tunnel ingress/DNS, and every HTTP verification"
log "coolify version: ${coolify_version}"
log "stages: ${stages}"
log "dry run: ${dry_run}"

ssh_opts=(-i "$ssh_key" -o BatchMode=yes -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new)
remote_dir='/tmp/ovh-provision'
remote_touched=0
env_file=''

cleanup_remote() {
  # Fail-safe: remove remote stage material (including stage.env with all
  # injected credentials) on EVERY exit path, not just success. Best-effort
  # by design — must never mask the real exit code — but a failure here is
  # loud so a leftover secret file cannot go unnoticed.
  if [ "$dry_run" -eq 1 ] || [ "$remote_touched" -eq 0 ]; then
    return 0
  fi
  # Client-side expansion is intentional: remote_dir is a runner-local constant.
  # shellcheck disable=SC2029
  if ssh "${ssh_opts[@]}" "${ssh_user}@${host}" "rm -rf ${remote_dir}" 2>/dev/null; then
    log 'remote stage material removed.'
  else
    echo "WARNING: could not remove remote stage material at ${host}:${remote_dir}; inspect manually." >&2
  fi
  return 0
}
trap 'cleanup_remote; rm -f "$env_file"' EXIT

want_stage() {
  case ",${stages}," in
    *,"$1",*) return 0 ;;
    *) return 1 ;;
  esac
}

if [ "$dry_run" -eq 1 ]; then
  log 'DRY-RUN: verify SSH connectivity (ssh -BatchMode user@host true)'
  log 'DRY-RUN: retrieve from OpenBao by name only (SSH public key, tunnel token, service-token pair, R2 triple) + require ROOT_* env'
  log 'DRY-RUN: scp stage scripts + generated 0600 env file to /tmp/ovh-provision on the target'
  want_stage bootstrap && log 'DRY-RUN: remote sudo BOOTSTRAP_TARGET_HOST/BOOTSTRAP_SSH_PUBLIC_KEY bash bootstrap-vps.sh + verify docker hello-world'
  want_stage coolify && log "DRY-RUN: remote sudo COOLIFY_TARGET_HOST/COOLIFY_DOMAIN/COOLIFY_VERSION/ROOT_* bash provision-coolify.sh (FQDN + firewall + origin smoke) + verify origin login"
  want_stage edge && log 'DRY-RUN: remote sudo TUNNEL_TARGET_HOST/TUNNEL_DOMAIN/CLOUDFLARED_TUNNEL_TOKEN/CF_ACCESS_* bash configure-tunnel-access.sh + verify domain login HTTP 200 locally'
  want_stage backup && log 'DRY-RUN: provision remote r2.env (0600) from OpenBao via stdin pipe + remote sudo bash schedule-coolify-backup.sh + verify timer + R2 object'
  log 'DRY-RUN: delete env file on both ends; report per-stage pass/fail (fail closed)'
  exit 0
fi

command -v bao >/dev/null 2>&1 || { echo 'bao CLI is required on the operator machine.' >&2; exit 2; }
export BAO_ADDR="$bao_addr"
bao_get() { bao kv get "-field=$2" "secret/projects/ovhcloud/$1"; }

log 'checking SSH connectivity...'
run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" true
log 'SSH connectivity ok.'

log 'retrieving stage credentials from OpenBao (names only, values never printed)...'
ssh_pub="$(bao_get COOLIFY_SSH_PUBLIC_KEY value)"
tunnel_token="$(bao_get COOLIFY_TUNNEL_TOKEN tunnel_token)"
svc_id="$(bao_get COOLIFY_ACCESS_SERVICE_TOKEN client_id)"
svc_secret="$(bao_get COOLIFY_ACCESS_SERVICE_TOKEN client_secret)"
r2_ak="$(bao_get COOLIFY_R2 access_key_id)"
r2_sk="$(bao_get COOLIFY_R2 secret_access_key)"
r2_bucket="$(bao_get COOLIFY_R2 bucket)"
for v in ssh_pub tunnel_token svc_id svc_secret r2_ak r2_sk r2_bucket; do
  if [ -z "${!v}" ]; then echo "OpenBao escrow missing for ${v}; refusing to continue." >&2; exit 2; fi
done
log 'OpenBao retrieval ok (all required fields present).'

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$(mktemp /tmp/ovh-provision-env.XXXXXX)"
chmod 600 "$env_file"
trap 'rm -f "$env_file"' EXIT
cat >"$env_file" <<ENV_EOF
BOOTSTRAP_TARGET_HOST=${host}
BOOTSTRAP_SSH_PUBLIC_KEY=${ssh_pub}
COOLIFY_TARGET_HOST=${host}
COOLIFY_DOMAIN=${dashboard_host}
COOLIFY_VERSION=${coolify_version}
ROOT_USERNAME=${ROOT_USERNAME}
ROOT_USER_EMAIL=${ROOT_USER_EMAIL}
ROOT_USER_PASSWORD=${ROOT_USER_PASSWORD}
TUNNEL_TARGET_HOST=${host}
TUNNEL_DOMAIN=${zone}
CLOUDFLARED_TUNNEL_TOKEN=${tunnel_token}
CF_ACCESS_CLIENT_ID=${svc_id}
CF_ACCESS_CLIENT_SECRET=${svc_secret}
COOLIFY_SERVICE_TOKEN_CLIENT_ID=${svc_id}
COOLIFY_SERVICE_TOKEN_CLIENT_SECRET=${svc_secret}
R2_ACCESS_KEY_ID=${r2_ak}
R2_SECRET_ACCESS_KEY=${r2_sk}
R2_ENDPOINT=${r2_endpoint}
R2_BUCKET=${r2_bucket}
AWS_DEFAULT_REGION=auto
ENV_EOF

log 'copying stage scripts + env file to the target...'
run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" "mkdir -p ${remote_dir}/lib && chmod 700 ${remote_dir} ${remote_dir}/lib"
remote_touched=1
run scp -p "${ssh_opts[@]}" "$repo_root/scripts/bootstrap-vps.sh" "$repo_root/scripts/provision-coolify.sh" \
  "$repo_root/scripts/configure-tunnel-access.sh" "$repo_root/scripts/schedule-coolify-backup.sh" \
  "${ssh_user}@${host}:${remote_dir}/"
run scp -p "${ssh_opts[@]}" "$repo_root/scripts/lib/preserved-guard.sh" \
  "${ssh_user}@${host}:${remote_dir}/lib/"
run scp -p "${ssh_opts[@]}" "$env_file" "${ssh_user}@${host}:${remote_dir}/stage.env"
run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" "chmod 600 ${remote_dir}/stage.env"

remote_stage() {
  local name="$1" script="$2"
  log "== remote stage: ${name} =="
  run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" \
    "set -a; source ${remote_dir}/stage.env; set +a; sudo -E bash ${remote_dir}/${script}"
  log "remote stage ${name} exited 0."
}

if want_stage bootstrap; then
  remote_stage bootstrap bootstrap-vps.sh
  run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" 'docker run --rm hello-world >/dev/null'
  log 'bootstrap verified: docker hello-world runs on the target.'
fi

if want_stage coolify; then
  remote_stage coolify provision-coolify.sh
  run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" 'curl -fsS --max-time 20 http://127.0.0.1:8000/login -o /dev/null'
  log 'coolify verified: origin login route answers on the target.'
fi

if want_stage edge; then
  remote_stage edge configure-tunnel-access.sh
  smoke_code="$(curl -sS -o /dev/null -w '%{http_code}' --cookie-jar /dev/null --max-time 30 \
    -H "CF-Access-Client-Id: ${svc_id}" -H "CF-Access-Client-Secret: ${svc_secret}" \
    "https://${dashboard_host}/login")"
  if [ "$smoke_code" = '200' ]; then
    log "edge verified: https://${dashboard_host}/login -> HTTP 200 (service token accepted)."
  else
    echo "edge verification failed: HTTP ${smoke_code} (required 200)." >&2
    exit 1
  fi
fi

if want_stage backup; then
  log 'provisioning remote R2 env from OpenBao values via stdin pipe...'
  {
    printf 'R2_ACCESS_KEY_ID=%s\n' "$r2_ak"
    printf 'R2_SECRET_ACCESS_KEY=%s\n' "$r2_sk"
    printf 'R2_ENDPOINT=%s\n' "$r2_endpoint"
    printf 'R2_BUCKET=%s\n' "$r2_bucket"
    printf 'AWS_DEFAULT_REGION=auto\n'
  } | run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" \
    'sudo mkdir -p /root/coolify-backup && sudo tee /root/coolify-backup/r2.env >/dev/null && sudo chmod 600 /root/coolify-backup/r2.env'
  run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" "sudo bash ${remote_dir}/schedule-coolify-backup.sh"
  run ssh "${ssh_opts[@]}" "${ssh_user}@${host}" 'sudo systemctl is-enabled coolify-backup.timer | grep -q enabled'
  log 'backup verified: coolify-backup.timer enabled on the target (first backup runs during install).'
fi

trap - EXIT
cleanup_remote
rm -f "$env_file"
log 'remote provisioning complete: all requested stages passed with verification; stage material removed from both ends.'
